name: convoy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  provider: ^6.1.5
  cloud_firestore: ^5.6.7
  firebase_database: ^11.3.5
  google_maps_flutter: ^2.12.2
  intl: ^0.20.2
  intl_utils: ^2.8.10
  geocoding: ^3.0.0
  geolocator: ^14.0.1
  location: ^8.0.0
  permission_handler: ^12.0.0+1
  flutter_polyline_points: ^2.0.0
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^16.3.2
  google_maps_utils: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/